M48
; DRILL file {KiCad (6.0.11)} date Thu Mar 13 12:33:18 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-13T12:33:18+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1280
%
G90
G05
T2
X2.7953Y-5.5059
T3
X3.6608Y-5.4539
X4.1108Y-5.4539
T1
G00X2.8051Y-5.6791
M15
G01X2.7854Y-5.6791
M16
G05
T0
M30
